name: Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: pip

    # Install uv and enable cache keyed by pyproject/uv.lock
    - name: Install uv
      uses: astral-sh/setup-uv@v6
        
    # Install project + dev deps declared in dependency groups
    - name: Sync dependencies
      run: uv sync --extra docs --extra dev

    - name: Build documentation
      run: |
        cd docs
        # Create a symlink to README.md if it doesn't exist
        if [ ! -f README.md ]; then
          ln -s ../README.md .
        fi
        uv run generate_docs.py
        make html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        force_orphan: true
